Updated eslint version
Relates to this issue https://github.com/eslint/eslint/issues/2304

```shell
standard: Unexpected linter output:

TypeError: Cannot read property 'type' of undefined
    at isExported (/Users/XXX/XXX/node_modules/standard/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
```